name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  phplint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Lint with PHP-CS-Fixer
      run: composer run-script lint

    - name: Run tests
      run: composer test
